<a href="https://colab.research.google.com/github/aso1801028/AI_teach2020/blob/master/20201009AI0205_selectAlgo.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
from sklearn.utils.testing import all_estimators
import warnings
from sklearn.svm import SVC

In [ ]:
#!pip uninstall scikit-learn
#!pip install scikit-learn==0.20 --igore-installed

In [ ]:
import urllib.request as req
url = "https://raw.githubusercontent.com/pandas-dev/pandas/master/pandas/tests/io/data/csv/iris.csv"
savefile = "iris.csv"
req.urlretrieve(url,savefile)
iris_data = pd.read_csv(savefile, encoding="utf-8")
iris_data.head()

SepalLength  SepalWidth  PetalLength  PetalWidth         Name
0          5.1         3.5          1.4         0.2  Iris-setosa
1          4.9         3.0          1.4         0.2  Iris-setosa
2          4.7         3.2          1.3         0.2  Iris-setosa
3          4.6         3.1          1.5         0.2  Iris-setosa
4          5.0         3.6          1.4         0.2  Iris-setosa

In [ ]:
y=iris_data.loc[:,"Name"]
x=iris_data.loc[:,["SepalLength","SepalWidth","PetalLength","PetalWidth"]]
print(y.head())
print(x.head())

0    Iris-setosa
1    Iris-setosa
2    Iris-setosa
3    Iris-setosa
4    Iris-setosa
Name: Name, dtype: object
   SepalLength  SepalWidth  PetalLength  PetalWidth
0          5.1         3.5          1.4         0.2
1          4.9         3.0          1.4         0.2
2          4.7         3.2          1.3         0.2
3          4.6         3.1          1.5         0.2
4          5.0         3.6          1.4         0.2


In [ ]:
x_train, x_test, y_train, y_test= train_test_split(x,y, test_size=0.2, train_size=0.8, shuffle=True)
print(x_train.head())
print(y_train.head())
print(x_test.head())
print(y_test.head())

     SepalLength  SepalWidth  PetalLength  PetalWidth
41           4.5         2.3          1.3         0.3
65           6.7         3.1          4.4         1.4
143          6.8         3.2          5.9         2.3
131          7.9         3.8          6.4         2.0
147          6.5         3.0          5.2         2.0
41         Iris-setosa
65     Iris-versicolor
143     Iris-virginica
131     Iris-virginica
147     Iris-virginica
Name: Name, dtype: object
     SepalLength  SepalWidth  PetalLength  PetalWidth
3            4.6         3.1          1.5         0.2
117          7.7         3.8          6.7         2.2
109          7.2         3.6          6.1         2.5
106          4.9         2.5          4.5         1.7
28           5.2         3.4          1.4         0.2
3         Iris-setosa
117    Iris-virginica
109    Iris-virginica
106    Iris-virginica
28        Iris-setosa
Name: Name, dtype: object


In [ ]:
allAlgorithms = all_estimators(type_filter="classifier")
warnings.filterwarnings('ignore')

In [ ]:
for (name,algorithm) in allAlgorithms:

  try:
    clf = algorithm()
    clf.fit(x_train, y_train)
    y_pred = clf.predict(x_test)
    print(name,"の正解率",accuracy_score(y_test,y_pred))


  except:
    print("エラー")
  #except Exception as e:
    #print("\033[31m", "Error: \033[0m", name, ":", e.args)
    
  #else:
    #print("正常系です")
    #pass

AdaBoostClassifier の正解率 0.9333333333333333
BaggingClassifier の正解率 0.9333333333333333
BernoulliNB の正解率 0.23333333333333334
CalibratedClassifierCV の正解率 0.9666666666666667
CategoricalNB の正解率 0.9
エラー
エラー
ComplementNB の正解率 0.7666666666666667
DecisionTreeClassifier の正解率 0.9333333333333333
DummyClassifier の正解率 0.36666666666666664
ExtraTreeClassifier の正解率 0.9333333333333333
ExtraTreesClassifier の正解率 0.9333333333333333
GaussianNB の正解率 0.9333333333333333
GaussianProcessClassifier の正解率 0.9666666666666667
GradientBoostingClassifier の正解率 0.9333333333333333
HistGradientBoostingClassifier の正解率 0.9333333333333333
KNeighborsClassifier の正解率 0.9333333333333333
LabelPropagation の正解率 0.9333333333333333
LabelSpreading の正解率 0.9333333333333333
LinearDiscriminantAnalysis の正解率 0.9666666666666667
LinearSVC の正解率 0.9666666666666667
LogisticRegression の正解率 0.9333333333333333
LogisticRegressionCV の正解率 0.9666666666666667
MLPClassifier の正解率 0.9666666666666667
エラー
MultinomialNB の正解率 0.8
NearestCentroid の正解率 0.9
NuSVC の

In [ ]:
from sklearn.model_selection import KFold
from sklearn.model_selection import cross_val_score

In [ ]:
kfold_cv = KFold(n_splits=5, shuffle=True)
for(name,algorithm)in allAlgorithms:
  try:
    clf = algorithm()
    if hasattr(clf,"score"):
      scores = cross_val_score(clf, x, y, cv=kfold_cv)
      print(name,"の正解率=")
      print(scores)
  except:
    pass

AdaBoostClassifier の正解率=
[0.93333333 0.96666667 0.86666667 0.96666667 0.9       ]
BaggingClassifier の正解率=
[0.9        0.96666667 0.96666667 0.96666667 0.96666667]
BernoulliNB の正解率=
[0.23333333 0.3        0.16666667 0.23333333 0.16666667]
CalibratedClassifierCV の正解率=
[0.93333333 0.93333333 0.83333333 0.86666667 1.        ]
CategoricalNB の正解率=
[0.96666667 0.86666667 0.93333333 0.96666667 0.9       ]
CheckingClassifier の正解率=
[nan nan nan nan nan]
ComplementNB の正解率=
[0.7        0.56666667 0.66666667 0.66666667 0.73333333]
DecisionTreeClassifier の正解率=
[0.93333333 1.         0.93333333 0.93333333 1.        ]
DummyClassifier の正解率=
[0.26666667 0.26666667 0.46666667 0.3        0.36666667]
ExtraTreeClassifier の正解率=
[0.93333333 1.         0.86666667 0.96666667 0.93333333]
ExtraTreesClassifier の正解率=
[1.         0.9        1.         0.9        0.93333333]
GaussianNB の正解率=
[0.96666667 0.93333333 0.93333333 0.96666667 0.96666667]
GaussianProcessClassifier の正解率=
[0.93333333 0.96666667 0.96666667 0.93

In [ ]:
from sklearn.model_selection import cross_validate

In [ ]:
kfold_cv = KFold(n_splits=5, shuffle=True)
for(name,algorithm)in allAlgorithms:
  try:
    clf = algorithm()
    if hasattr(clf,"score"):
      scores = cross_validate(clf, x, y, cv=kfold_cv)
      print(name,"の正解率=")
      print(scores)
  except:
    pass

AdaBoostClassifier の正解率=
{'fit_time': array([0.07848883, 0.06727052, 0.06782603, 0.06746626, 0.07652402]), 'score_time': array([0.00787568, 0.00687528, 0.0067966 , 0.00692248, 0.00697947]), 'test_score': array([0.93333333, 1.        , 0.96666667, 0.86666667, 0.9       ])}
BaggingClassifier の正解率=
{'fit_time': array([0.01583862, 0.01429176, 0.01420927, 0.01517153, 0.01448584]), 'score_time': array([0.00213242, 0.00211692, 0.00219893, 0.00219703, 0.00217295]), 'test_score': array([0.93333333, 0.9       , 0.93333333, 1.        , 0.96666667])}
BernoulliNB の正解率=
{'fit_time': array([0.00355577, 0.00283527, 0.00311422, 0.00202012, 0.00199819]), 'score_time': array([0.0018816 , 0.00176167, 0.00108504, 0.00105286, 0.00104427]), 'test_score': array([0.2       , 0.2       , 0.23333333, 0.3       , 0.3       ])}
CalibratedClassifierCV の正解率=
{'fit_time': array([0.06253529, 0.06053925, 0.05957508, 0.05806231, 0.06308031]), 'score_time': array([0.00201559, 0.00197625, 0.00194788, 0.00240993, 0.0020167

In [ ]:
from sklearn.model_selection import GridSearchCV
from sklearn.svm import SVC

In [ ]:
#
parameters = [
              #3パターン
              { "C":[1, 10, 100, 1000], "kernel":["linear"] },
              { "C":[1, 10, 100, 1000], "kernel":["rbf"], "gamma":[0.001, 0.0001] },
              { "C":[1, 10, 100, 1000], "kernel":["sigmoid"], "gamma":[0.001, 0.0001] }         
]

#普通の学習
clf = SVC()
clf.fit(x_train, y_train)
y_pred = clf.predict(x_test)
print("普通の学習の正解率 = ", accuracy_score(y_test,y_pred))

#グリッドサーチ
#
kfold_cv = KFold(n_splits=5, shuffle=True )
#
clf_gird = GridSearchCV( SVC(), parameters, cv=kfold_cv)
clf_gird.fit(x_train, y_train)
print("最適なパラメーター = ", clf_gird.best_estimator_)
y_pred = clf_gird.predict(x_test)
print("グリッドサーチの学習の正解率 = ", accuracy_score(y_test,y_pred))


普通の学習の正解率 =  0.9666666666666667
最適なパラメーター =  SVC(C=1, break_ties=False, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma='scale', kernel='linear',
    max_iter=-1, probability=False, random_state=None, shrinking=True,
    tol=0.001, verbose=False)
グリッドサーチの学習の正解率 =  1.0


In [ ]:
import numpy as np
a = np.array([1,2,3,4,5])
print(a)
print(type(a))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [ ]:
b = np.array([[1,2,3],[4,5,6]])
print(b)

[[1 2 3]
 [4 5 6]]


In [ ]:
print(np.zeros(10))
print(np.zeros((3,2)))
print(np.ones(2))

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[[0. 0.]
 [0. 0.]
 [0. 0.]]
[1. 1.]


In [ ]:
print(np.arange(5))
print(np.arange(2,9))
print(np.arange(5,8,0.5))

[0 1 2 3 4]
[2 3 4 5 6 7 8]
[5.  5.5 6.  6.5 7.  7.5]


In [ ]:
a = np.array([1,2,3,4,5])
b = a*2
print(b)
x = np.arange(10)
print(x)
y=3*x + 5
print(y)

[ 2  4  6  8 10]
[0 1 2 3 4 5 6 7 8 9]
[ 5  8 11 14 17 20 23 26 29 32]


In [ ]:
a=np.array([[1,2,3],[4,5,6]])
print(a)
print(a.shape)

b=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(b)
print(b.shape)

[[1 2 3]
 [4 5 6]]
(2, 3)
[[1 2 3]
 [4 5 6]
 [7 8 9]]
(3, 3)


In [ ]:
a = np.array([[1,2,3],[4,5,6]])
print("a=",a)
b=a.flatten()
print("b=",b)

a=np.array([[1,2,3],[4,5,6]])
print(a)
b = a.reshape(3,2)
print(b)

a= [[1 2 3]
 [4 5 6]]
b= [1 2 3 4 5 6]
[[1 2 3]
 [4 5 6]]
[[1 2]
 [3 4]
 [5 6]]


In [ ]:
v = np.array([[1,2,3],[4,5,6],[7,8,9]])
a=v[0]
print(a) #2次元配列の1行目
b=v[1:]
print(b) #1行目以降
c=v[:,0]
print(c) #すべての行の0列目

[1 2 3]
[[4 5 6]
 [7 8 9]]
[1 4 7]
